apiVersion: v1
kind: Service
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: sistema-noticias